name = "Hewlett Packard Enterprise"
description = "ThreeFold's premier partner for certified ThreeFold Farming hardware. HPE enables customers to accelerate business outcomes by driving new business models, creating new customer and employee experiences, and increasing operational efficiency today and into the future."
stars = 5
sectionID = 3
rank = 1
url = "https://wiki.threefold.io/#/hpe_eco"
