name = "flowgen"
description = "Rooted in motorsports aerodynamics flowgen develops & produces revolutionary small wind turbines. These turbines can be installed virtually anywhere without the need for high masts or deep foundations. This has a huge impact on costs and make it possible to now deliver power to the most remote & poor parts of the world, exactly the same parts ThreeFold wants to push internet capacity to. Making this partnership a very logical step for both parties."
stars = 5
url = "http://www.flowgen.com/"
