name = "SelfKey"
description = "SelfKey is a fast-growing blockchain startup developing digital identity solutions that empowers individuals and corporations to truly own, control, and manage their identity data."
stars = 5
rank = 10
url = "https://selfkey.org"
