name = "SelfKey"
description = "SelfKey is a fast-growing blockchain startup developing digital identity solutions that empowers individuals and corporations to truly own, control, and manage their identity data."
stars = 5
sectionID = 2
rank = 4
url = "https://wiki.threefold.io/#/selfkey"
