name = "Harmony"
description = "Harmony is a fast and open blockchain for decentralized applications. Its protocol has achieved secure and random state sharding, being the first sharded Proof of Stake on production."
stars = 5
sectionID = 2
rank = 4
url = "https://wiki.threefold.io/#/harmony"
