name = "Liquid"
description = "The world’s most comprehensive and secure trading platform. Buy and sell Bitcoin, Ethereum, XRP and many other cryptocurrencies with fiat or crypto."
star = 5
sectionID = 4
rank = 2
url = "https://www.liquid.com/?affiliate=kmOSQysu714987"
