name = "Liquid"
description = "the world’s most comprehensive and secure trading platform. Buy and sell Bitcoin, Ethereum, XRP and many other cryptocurrencies with fiat or crypto."
star = "5"
url = "https://www.liquid.com/?affiliate=kmOSQysu714987"
