name = "Jimber"
description = "Jimber is one of ThreeFold’s main software partners. Their team is responsible for building the first ADapps to be ran on our grid. With a background in security enterprise solutions they are a great fit into building out a suite of apps like: the Threefold Mobile wallet, 3bot App, Decentralized Video Conferencing, Browser-in-Browser, and more."
stars = 5
url = "https://jimber.org/"
