name = "Jimber"
description = "Jimber is one of ThreeFold’s main software partners. Their team is responsible for building the first ADapps to be run on our grid. With a background in security enterprise solutions they are an optimal partner for building out a suite of apps like the ThreeFold Mobile wallet, 3Bot App, Decentralized Video Conferencing, Browser-in-Browser, and more."
stars = 5
rank = 10
url = "https://jimber.org/"
