name = "WaykiChain"
description = "WaykiChain(WICC) is a high-performing finance-centric public blockchain that provides decentralized finance infrastructure for dApps through core-layer implementation of decentralized exchanges (DEX) and crypto-asset backed stablecoin (WUSD) technologies while adopting the dPoS+pBFT consensus algorithm making a highly Blockchain platform"
stars = 5
rank = 6
url = "https://www.waykichain.com/"
