name = "TomoChain"
description = "TomoChain is a scalable blockchain, powered via Proof-of-Stake Voting consensus and used commercially by companies globally. Their mission is to accelerate the onboarding of millions of users by empowering today’s applications with technology that masks the friction of Blockchain, all while retaining its underlying benefits."
stars = 5
rank = 14
url = "https://tomochain.com/"
